package com.uit.userservice.mapper;

import com.uit.userservice.dto.request.CreateUserRequest;
import com.uit.userservice.dto.response.UserResponse;
import com.uit.userservice.entity.User;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

@Mapper(componentModel = "spring")
public interface UserMapper {
    
    @Mapping(target = "userId", ignore = true)     // Auto-generated by @GeneratedValue
    @Mapping(target = "status", ignore = true)      // Has default value
    @Mapping(target = "createdAt", ignore = true)   // Auto-generated by @CreationTimestamp
    User toEntity(CreateUserRequest dto);

    UserResponse toResponseDto(User entity);
}