server:
  port: 4001
  max-http-request-header-size: 64KB

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/fortressbank-realm
  
  data:
    redis:
      host: ${SPRING_REDIS_HOST:redis}
      port: 6379
  
  jpa:
    hibernate:
      ddl-auto: update