# =============================================================================
# TRANSACTION SERVICE - PRODUCTION CONFIGURATION
# =============================================================================
# This configuration extends/overrides base configuration for production
# Use with: SPRING_PROFILES_ACTIVE=prod
# =============================================================================

server:
  port: 4004
  max-http-request-header-size: 64KB

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          # Production: Use HTTPS Keycloak endpoint
          issuer-uri: ${JWT_ISSUER_URI:https://auth.fortressbank.com/realms/fortressbank-realm}

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    # Connection pool hardening
    hikari:
      maximum-pool-size: 15  # Higher for transaction-heavy service
      minimum-idle: 3
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000
      connection-test-query: SELECT 1
      leak-detection-threshold: 60000

  data:
    redis:
      host: ${SPRING_REDIS_HOST:redis}
      port: ${SPRING_REDIS_PORT:6379}
      # PRODUCTION: Redis password authentication
      password: ${SPRING_REDIS_PASSWORD}
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 10
          max-idle: 8
          min-idle: 2
          max-wait: 2000ms

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:rabbitmq}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}
    virtual-host: ${SPRING_RABBITMQ_VIRTUAL_HOST:fortressbank}
    # Production: Enable SSL
    # ssl:
    #   enabled: true
    #   validate-server-certificate: true
    # Connection retry
    connection-timeout: 10000
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.batch_size: 25
        order_inserts: true
        order_updates: true

  sql:
    init:
      mode: never

jwt:
  issuer-uri: ${JWT_ISSUER_URI:https://auth.fortressbank.com/realms/fortressbank-realm}

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when_authorized
      probes:
        enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

# Logging
logging:
  level:
    root: WARN
    com.uit.transactionservice: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN

# Eureka Configuration
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://discovery:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${random.value}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

stripe:
  api-key: ${STRIPE_SECRET_KEY}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET}
  connect-account-id: ${STRIPE_CONNECT_ACCOUNT_ID}
  payout:
    timeout-seconds: 30
    currency: ${STRIPE_CURRENCY:usd}
    retry:
      max-attempts: 3
      backoff-delay-ms: 2000