package com.uit.userservice.entity;

public enum AuditAction {
    LOGIN_ATTEMPT,
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    PASSWORD_CHANGE,
    MFA_ENABLED,
    MFA_DISABLED,
    ACCOUNT_LOCKED,
    ACCOUNT_UNLOCKED,
    PROFILE_UPDATE,
    STATUS_CHANGE,
    ROLE_CHANGE,
    BRANCH_CHANGE,
    PASSWORD_RESET_REQUEST,
    PASSWORD_RESET_COMPLETE,
    ACCOUNT_CREATED,
    ACCOUNT_CLOSED,
    SUSPICIOUS_ACTIVITY
}
