package com.uit.userservice.entity;

public enum SecurityEventType {
    UNUSUAL_LOGIN_LOCATION,
    MULTIPLE_FAILED_LOGINS,
    PASSWORD_BRUTE_FORCE_ATTEMPT,
    SUSPICIOUS_IP_ADDRESS,
    MFA_FAILURE,
    SESSION_HIJACKING_ATTEMPT,
    CONCURRENT_LOGIN_ATTEMPT,
    UNAUTHORIZED_ACCESS_ATTEMPT,
    UNUSUAL_TRANSACTION_PATTERN,
    DEVICE_CHANGE,
    API_ABUSE,
    DATA_EXPORT_ATTEMPT,
    CONFIGURATION_CHANGE,
    PERMISSION_ESCALATION_ATTEMPT,
    ACCOUNT_LOCKOUT,
    DATABASE_ATTACK_ATTEMPT
}
