spring:
    config:
      import: optional:configserver:http://config-server:8888
    application:
      name: discovery-service

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
